### ISSUE TITLE
Release 3.9.1 is suggesting some odd-looking indent changes

### ISSUE THREAD

**Issue by phil-davis** [PHP-CS-Fixer/PHP-CS-Fixer#6470]
## Bug report
```
php -d zend.enable_gc=0 vendor-bin/owncloud-codestyle/vendor/bin/php-cs-fixer fix -v --diff --allow-risky yes --dry-run
PHP CS Fixer 3.9.1 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.30
```

Prior to 3.9.1 the code-style checks were passing. Now I get code-style problems reported like in PR https://github.com/owncloud/encryption/pull/351
https://drone.owncloud.com/owncloud/encryption/2552/1/3

### Code snippet that reproduces the problem
https://github.com/owncloud/encryption/blob/master/templates/settings-admin.php is an example.
To keep php-cs-fixer happy, lines 13 to 25 have to become:
```
		<label id="encryptionType">
			<?php
			$masterKey = \OC::$server->getAppConfig()->getValue('encryption', 'useMasterKey', '0');
		$userSpecificKey = \OC::$server->getAppConfig()->getValue('encryption', 'userSpecificKey', '');
		if ($masterKey !== '0') {
			p($l->t("Encryption type: Master Key"));
		} else {
			if ($userSpecificKey !== "") {
				p($l->t("Encryption type: User Specific Key"));
			}
		}
		?>
```

After the `$masterKey` line, php-cs-fixer decides that the next lines(s) need to have their indent reduced.

That looks odd to me - is there a bug/regression somewhere? Or is this really the indent that php-cs-fixer intends to suggest?

**Comment by phil-davis** [comment]
The settings used in ownCloud CI are:
https://github.com/owncloud/coding-standard/blob/master/src/Config.php

**Comment by phil-davis** [comment]
Here is a long list of indent changes that 3.9.1 would like to make to the https://github.com/owncloud/core repo:
https://github.com/owncloud/core/pull/40196/files

**Comment by mvorisek** [comment]
I confirm the issues with the `braces` rule in v3.8.1 and here are more examples of bad fixes:

```diff
             if (!array_key_exists(0, $seed)) {
-               // allow this method to be used to merge seeds without class name
+          // allow this method to be used to merge seeds without class name
             }
```

multiline anonymous function in method call on 1 line must stay indented as before:

```diff
         $m->onHookDynamic('inc', function () use ($m) {
             return clone $m;
-        }, function ($ignoreObject, $ignore1st, int &$value) {
-            ++$value;
-        });
+            }, function ($ignoreObject, $ignore1st, int &$value) {
+                ++$value;
+            });
```

`switch` has some issues as well:

![image](https://user-images.githubusercontent.com/2228672/178251102-34c890a5-36c6-4767-9f44-7e00ef84af62.png)

https://github.com/atk4/data/blob/fdfaac49106e490d35698edcab1748ae84683e2f/src/Field.php#L174

![image](https://user-images.githubusercontent.com/2228672/178251281-44c15ea9-f78d-4d32-bdbb-140ef3769da2.png)

https://github.com/atk4/data/blob/fdfaac49106e490d35698edcab1748ae84683e2f/src/Persistence/Array_.php#L447

it seems it happends when there is `if` before

**Comment by sebastianbergmann** [comment]
> I confirm the issues with the `braces` rule in v3.8.1 and here are more examples of bad fixes:

With "v3.8.1" you mean v3.9.1, right?

**Comment by phil-davis** [comment]
> > I confirm the issues with the `braces` rule in v3.8.1 and here are more examples of bad fixes:
> 
> With "v3.8.1" you mean v3.9.1, right?

@mvorisek ^

**Comment by mvorisek** [comment]
> > I confirm the issues with the `braces` rule in v3.8.1 and here are more examples of bad fixes:
> 
> With "v3.8.1" you mean v3.9.1, right?

yes, typo, I meant the latest v3.9.1

**Comment by keradus** [comment]
@julienfalque , do I remember right that you had a chance to check this code recently? maybe you can look on this report, please?

**Comment by julienfalque** [comment]
#6473 should fix wrong indentation after a control structure within a switch case. I'll have a look at other cases shortly.

**Comment by julienfalque** [comment]
@alexander-schranz This one looks expected to me: the first `addOption` call is not on a newline so there is no reason to indent arguments twice. What about moving the first call to a newline?
```php
class A
{
    protected function configure()
    {
        $this
            ->addOption(
                'force',
                'f',
                InputOption::VALUE_NONE,
                'Force recovery of tree. Without it, an analysis of the tree is performed'
            )
            ->addOption(
                'fix-depth',
                'd',
                InputOption::VALUE_NONE,
                'Analyse depths of categories and fixes depth gaps as well as depths > 0 without a parent'
            );
      }
}
```

**Comment by alexander-schranz** [comment]
@julienfalque was also what I was doing know. Still the change of php-cs-fixer did feel strange for me :)

**Comment by keradus** [comment]
@julienfalque , is there any open topic from this issue, after all the PRs merged?

**Comment by julienfalque** [comment]
I need to have a look at @phil-davis' link but I think the main remaining issue is indentation in PHP within HTML, which might be tricky.

**Comment by mvorisek** [comment]
I tested the v3.9.4 and all issues I described above are gone. Thank you for fixing it promtly 🥇

**Comment by mvorisek** [comment]
@julienfalque still one difference vs. prev minor version/v3.8:
```
    1) ui/src/Persistence/Ui.php (braces)
      ---------- begin diff ----------
--- /__w/ui/ui/src/Persistence/Ui.php
+++ /__w/ui/ui/src/Persistence/Ui.php
@@ -199,8 +199,8 @@
                 $value = parent::_typecastSaveField($field, $value);
                 break;
-            // SECURTIY: Do not unserialize any user input
-            // https://github.com/search?q=unserialize+repo%3Adoctrine%2Fdbal+path%3A%2Fsrc%2FTypes
+                // SECURTIY: Do not unserialize any user input
+                // https://github.com/search?q=unserialize+repo%3Adoctrine%2Fdbal+path%3A%2Fsrc%2FTypes
             case 'object':
             case 'array':
                 throw new Exception('Object serialization is not supported');
      ----------- end diff -----------
```

I belive the original indentation is "more correct", as the case itself it ended by `break;`. WDYT, is it worth fixing it?

**Comment by christian-fries** [comment]
> @julienfalque still one difference vs. prev minor version/v3.8:
> 
> ```
>     1) ui/src/Persistence/Ui.php (braces)
>       ---------- begin diff ----------
> --- /__w/ui/ui/src/Persistence/Ui.php
> +++ /__w/ui/ui/src/Persistence/Ui.php
> @@ -199,8 +199,8 @@
>                  $value = parent::_typecastSaveField($field, $value);
>                  break;
> -            // SECURTIY: Do not unserialize any user input
> -            // https://github.com/search?q=unserialize+repo%3Adoctrine%2Fdbal+path%3A%2Fsrc%2FTypes
> +                // SECURTIY: Do not unserialize any user input
> +                // https://github.com/search?q=unserialize+repo%3Adoctrine%2Fdbal+path%3A%2Fsrc%2FTypes
>              case 'object':
>              case 'array':
>                  throw new Exception('Object serialization is not supported');
>       ----------- end diff -----------
> ```
> 
> I belive the original indentation is "more correct", as the case itself it ended by `break;`. WDYT, is it worth fixing it?

@mvorisek I agree, the original indentation makes more sense. I tested php-cs-fixer ^3.9 on some projects and was wondering why such lines get changed

**Comment by mvorisek** [comment]
another unexpected fix:
```
    1) data/src/Schema/TestCase.php (class_attributes_separation, braces)
      ---------- begin diff ----------
--- /__w/data/data/src/Schema/TestCase.php
+++ /__w/data/data/src/Schema/TestCase.php
@@ -67,7 +67,8 @@
                 }
                 $connection->getConnection()->getConfiguration()->setSQLLogger(
-                    null ?? new class($this) implements SQLLogger { // @phpstan-ignore-line
+                    null ?? new class($this) implements SQLLogger {
+                        // @phpstan-ignore-line
                         public function startQuery($sql, array $params = null, array $types = null): void
                         {
                             $test = TestCase::getTestFromBacktrace();
      ----------- end diff -----------
```

full file source code: https://github.com/atk4/data/blob/57aab906cc88e28ebea2b44be8293e57fc778021/src/Schema/TestCase.php#L70

**Comment by julienfalque** [comment]
@mvorisek I can't reproduce this one, can you try with latest `master`? Also, please submit new issues for new cases, tracking which cases is fixed or not here is becoming tedious.

**Comment by mvorisek** [comment]
> @mvorisek I can't reproduce this one, can you try with latest `master`? Also, please submit new issues for new cases, tracking which cases is fixed or not here is becoming tedious.

On my side, the issue is still present. Create https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6492 issue for it.

**Comment by keradus** [comment]
Hey!

We identified that `braces` fixer is too complex and has too many responsibilities. With that, we decided to **deprecate** it [ref #4885].

That also means that we will not be extending, changing the behaviour or fixing anything around `braces` fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.

If you see the issue that you reported to be present in one of the replacement rules, please report a new github issue.

Big thanks!
