### ISSUE TITLE
Remove unneeded parentheses in phpdoc

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6799]
## Feature request

Thanks to #6796 parenthesised phpdoc support has been added. This is a feature request to remove unneeded parentheses in phpdoc.

Example:

```
@var ((A|B)&(C))
```

and I expect the following fix:
```
@var (A|B)&C
```

**Comment by keradus** [comment]
mind to propose a PR, @mvorisek ?

**Comment by mvorisek** [comment]
I do not plan a PR for this by myself.

**Comment by mvorisek** [comment]
@Wirone please label this so the stale bot stays silent

**Comment by Wirone** [comment]
@mvorisek I won't do it, and please stop pointing out Stale Bot in each issue. The whole purpose of this action is to enforce backlog review once in a while, and labelling issues to skip it does not make sense. For now, there is only one scenario when we don't want Stale Bot to enter: milestone `long-term-ideas` with some kind of architectural plan for the future. Other issue and PRs will be under Stale Bot so we can verify quarterly if they're relevant ([I pointed it out already](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5950#issuecomment-1674646447), but I edited your comment so you could have miss it). Many times issues were fixed but were not closed because there wasn't reference ([recent example](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6699#issuecomment-1673113362)). This action is mostly for maintainers and I process every issue/PR marked as stale, so you really don't need to do anything, but you can help if you want, by providing information about current relevancy, so I have less to do 🙂. But please don't ping me and ask for skipping Stale Bot.

**Comment by keradus** [comment]
It could also be that idea is valid, but very little interest of community (eg nobody implementing) and out of focus for core team. Should we keep it open indefinitely, or let to close it as stale, and recover when it will get some attention (eg more community demand or someone creating the effort).

With that, I would identify stale issue to be "totally not a priority" (or already solved but forgot to close) and not "idea rejected, it is not allowed to go this path, we will never merge a PR for it"

**Comment by mvorisek** [comment]
I feel really bad to hear this. The noise from bots is really not good, as it only distracts [1]. If they close any issue, someone else will recreate another one sooner or later. Almost noone looks in the closed ones.

[1] some issues take years to fix/implement, should the discussions be really messed with stale bot posts every few months?

**Comment by Wirone** [comment]
@mvorisek I know how to use filters, but I don't want to review whole backlog all the time. I need an automated support to focus only on things that require real attention. I've proposed better explanation from Stale Bot in #7236 which should make it more clear to users.

> If they close any issue, someone else will recreate another one sooner or later. Almost noone looks in the closed ones.

Issue/PR won't be closed if there's any activity, so any of the interested users can comment, then `status/stale` will be removed and `status/to verify` will be added so maintainers can take a look at it again. Besides external activity, I process every stale notification I get (see below), but it takes time so don't expect instant reaction every time 🤷‍♂️.

> some issues take years to fix/implement, should the discussions be really messed with stale bot posts every few months?

It's not the final configuration of stale bot, we can tweak it in the future to exclude more issue from the bot, but we're still processing current backlog (when I started there were more than 300 issues). Anyway, when I process stale issues I hide comments from Bot so the timeline is cleaner. When we reduce backlog and it's easier to keep track of every opened issue/PR, we can get rid of Bot, but for now it's helpful from maintenance point of view.

> [2] I have 18 active/opened issues here. Please, do something, I do grant any permission to any bot to distract me every 5 (90 / 18) days.

I have notifications for the whole repo, so not only for mine, but also any other issues/PRs, yours too. I believe it's a part of being a maintainer, but please understand that there is also other side of that - to make it easier, I need automation.

PS. I'll mark our comments ass off-topic, if you want to discuss it further consider [creating discussion](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions).

**Comment by mvorisek** [comment]
In short, I would be very helpful if my efford in submitted issues and PRs will be valued and my brain saved from bots.

Based on your post, the bot is helpfull for you to review the issues on periodic basis. IIRC, addition/removal of GH label does not trigger notification. So the bot should actually not post any post. Then you can filter on the stale bot label. If relevant, you can close it, let the author know, and if not, remove the label, bot will kick in the next 90 days. Everyone will be happy.

**Comment by Wirone** [comment]
It's not only about me, bot messages trigger notification for all subscribed people so re-triage is spread across several people potentially interested in issue/PR. Many people reacted to this notification in a way that allowed me to close the issue after their feedback. Without this notification I would need to periodically check list of issues/PRs with `status/stale` label, which requires different approach - I already need to do like this for `status/to verify` and it's not the best one IMHO. I believe it's not that much to get few notifications every 3 months, but you can always opt-out from comments and subscribe only to status changes:

<img width="320" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/ee0a663c-3044-43dd-8c9d-4021962ce463">

But thanks for that suggestion, I'll keep it in mind.

**Comment by mvorisek** [comment]
dear bot, this is never stale topic

**Comment by Wirone** [comment]
There is no such thing like "never stale topic", since everything can be implemented/fixed in any PR which is not linked to the issue and the issue may be left open while it should be closed. As described in [Stale bot's comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6799#issuecomment-1945969945), the purpose of this is to be able to clear the backlog from outdated stuff. Yes, there's workaround that tells Stale Bot to ignore issue, but this particular report does not match criteria to be included in the `topic/core`. Just accept it 😉.

**Comment by mvorisek** [comment]
let's keep this PR open

**Comment by keradus** [comment]
this request is not considered as priority for core team members and nobody is working on it for over a year.
let's keep this PR closed.

this still doesn't prevent brave hero to work on implementation and have this incorporated into the codebase!
